export const defaultEvents = [
  {
    id: 'e1',
    title: 'Concierto de Rock en el Parque',
    image: 'https://rockalparque.gov.co/sites/default/files/styles/866_x_485/public/2023-09/IDARTES_RAP22_PLAZA_PRESS_26112022-MAT_6026-18.jpeg?itok=dlU4iAvV',
    date: '2025-07-20',
    time: '19:00',
    location: 'Chapinero',
    address: 'Parque Simón Bolívar, Av. Cra. 68 #63-00',
    type: 'Música',
    description: 'Un festival de rock con bandas locales e internacionales.',
  },
  {
    id: 'e2',
    title: 'Obra de Teatro: La Casa de Bernarda Alba',
    image: 'https://www.agendadehuelva.com/wp-content/uploads/2021/04/MGP6018-%C2%A9-marcosGpunto-scaled.jpg',
    date: '2025-07-22',
    time: '20:00',
    location: 'La Candelaria',
    address: 'Teatro Colón, Calle 10 #5-32',
    type: 'Teatro',
    description: 'Clásico de Federico García Lorca, adaptado para el público bogotano.',
  },
  {
    id: 'e3',
    title: 'Festival de Cine Independiente',
    image: 'https://imcine.gob.mx/media/2024/1/poster-finci.jpg',
    date: '2025-07-25',
    time: '18:00',
    location: 'Teusaquillo',
    address: 'Cinemateca de Bogotá, Carrera 3 #19-10',
    type: 'Cine',
    description: 'Proyección de cortometrajes y largometrajes de directores emergentes.',
  },
  {
    id: 'e4',
    title: 'Taller de Cerámica Artesanal',
    image: 'https://artesaniasdecolombia.com.co/Documentos/Contenido/34351_taller-oficio-alfareia-fidencio-cueltan-artesanias-colombia-2020-g.jpg',
    date: '2025-07-28',
    time: '10:00',
    location: 'Usaquén',
    address: 'Carrera 6A #117-45, Usaquén',
    type: 'Talleres',
    description: 'Aprende las técnicas básicas de la cerámica y crea tus propias piezas.',
  },
  {
    id: 'e5',
    title: 'Feria Gastronómica de La Candelaria',
    image: 'https://bogota.gov.co/sites/default/files/styles/1050px/public/eventos/2022-09/sabor_candelaria.jpg',
    date: '2025-08-01',
    time: '12:00',
    location: 'La Candelaria',
    address: 'Plaza de Bolívar, Carrera 7 #10-00',
    type: 'Ferias',
    description: 'Degusta los sabores tradicionales y modernos de la cocina colombiana.',
  },
  {
    id: 'e6',
    title: 'Exposición de Arte Moderno',
    image: 'https://www.escueladesarts.com/wp-content/uploads/galerias-de-arte.jpg',
    date: '2025-08-05',
    time: '09:00',
    location: 'Chapinero',
    address: 'Museo de Arte Moderno de Bogotá, Calle 24 #6-00',
    type: 'Arte',
    description: 'Una colección de obras de artistas contemporáneos.',
  },
  {
    id: 'e7',
    title: 'Noche de Jazz en Chapinero',
    image: 'https://hemmabogota.com/wp-content/uploads/2025/01/JAZZ.jpg',
    date: '2025-07-21',
    time: '21:00',
    location: 'Chapinero',
    address: 'The Jazz Joint, Calle 85 #12-25',
    type: 'Música',
    description: 'Disfruta de una velada con los mejores exponentes del jazz local.',
  },
  {
    id: 'e8',
    title: 'Stand-up Comedy: Risas Bogotanas',
    image: 'https://bogota.gov.co/sites/default/files/eventos/2024-08/showdecomedia.png',
    date: '2025-08-10',
    time: '20:30',
    location: 'Teusaquillo',
    address: 'Teatro Nacional La Castellana, Calle 95 #47-15',
    type: 'Teatro',
    description: 'Una noche llena de humor con comediantes emergentes de Bogotá.',
  },
  {
    id: 'e9',
    title: 'Ciclo de Cine Clásico: Películas Colombianas',
    image: 'https://panoramacultural.com.co/media/images/articulos/2023/04/09042513.jpg',
    date: '2025-07-26',
    time: '17:00',
    location: 'Suba',
    address: 'Biblioteca Pública Julio Mario Santo Domingo, Av. Calle 170 #67-51',
    type: 'Cine',
    description: 'Revive la época dorada del cine colombiano con proyecciones especiales.',
  },
  {
    id: 'e10',
    title: 'Clase Abierta de Salsa Caleña',
    image: 'https://studio11madrid.com/wp-content/uploads/blog/BNF1.jpg',
    date: '2025-07-29',
    time: '16:00',
    location: 'Fontibón',
    address: 'Centro Comercial Hayuelos, Calle 20 #82-52',
    type: 'Talleres',
    description: 'Aprende los pasos básicos de la salsa caleña en esta clase gratuita.',
  },
];